package com.feiqn.wyrm.logic.handlers.cutscene;

public enum CutsceneID {

    // STORY A
    // 0A
    // TODO: gather supplies, poke antal, enter, leave


    // 1A
    CSID_1A_ANTAL_ESCAPINGALIVE,
    CSID_1A_ANTAL_HELPME,
    CSID_1A_BALLISTA1,
    CSID_1A_BALLISTA2,
    CSID_1A_BALLISTA3,
    CSID_1A_LEIF_FLEEINGALONE,
    CSID_1A_LEIF_GETTINGINTHEBALLISTA,
    CSID_1A_LEIF_GOTAKILLWITHTHEBALLISTA,
    CSID_1A_LEIF_INEFFECTIVEATTACK,
    CSID_1A_LEIF_LEAVEMEALONE,
    CSID_1A_LEIF_NEEDTOESCAPE,
    CSID_1A_LEIF_SAVEDANTAL,

    CSID_1A_POST_LEIFANTAL_CAMPFIRE,
    CSID_1A_POST_LEIF_FOUNDANTAL,
    CSID_1A_POST_LEIF_SHOULDFINDANTAL,
    CSID_1A_POST_LEIF_ESCAPEDALONE,


    // 2A
    CSID_2A_PRE_LEIFANTAL_GATESARECLOSED,

    CSID_2A_LEIFANTAL_STEALTHINTOCITY,

    CSID_2A_POST_ANVIL_CAUGHTYOUSNEAKINGIN,
    CSID_2A_POST_TOHNI_SAWYOUSNEAKPASTGUARDS,


    // 3A









    // ===============================
    // STORY BA
    // 1BA


    // STORY BB
    // 1BB







    // ===============================
    // STORY CA
    // 1CA


    // STORY CB
    // 1CB

}
